### Gestion des imports

In [1]:
import numpy as np
import pandas as pd
import json

#### Récupération du csv

In [2]:
with open('employes_data_10_2024.json')as file:
    data = json.load(file)

#Checking of datas in the json
print(data)
print(data.keys())

#Split the datas in 3 distinct collections according to the subsidiary
TechCorp = data['TechCorp']
DesignWorks = data['DesignWorks']
ProjectLead = data['ProjectLead']

#Creation of 3 distincts Dataframe
TechCorp1 = pd.json_normalize(TechCorp)
DesignWorks1 = pd.json_normalize(TechCorp)
ProjectLead1 = pd.json_normalize(TechCorp)

ProjectLead1

{'TechCorp': [{'name': 'Helen', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 44, 'contract_hours': 37}, {'name': 'Quincy', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 48, 'contract_hours': 40}, {'name': 'Fred', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 33, 'contract_hours': 40}, {'name': 'Steve', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 32, 'contract_hours': 40}, {'name': 'Linda', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 34, 'contract_hours': 35}, {'name': 'Bob', 'job': 'Analyste', 'hourly_rate': 40, 'weekly_hours_worked': 35, 'contract_hours': 40}, {'name': 'Steve', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 50, 'contract_hours': 37}, {'name': 'Karen', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 33, 'contract_hours': 40}, {'name': 'Paul', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 30, 'contract_hours': 35}, {'name': 'Bob', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 48, 'contract_hours': 35}, {'name': 'Bob', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 45, 'contract_hours': 35}, {'name': 'Mike', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 33, 'contract_hours': 40}, {'name': 'Mike', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 43, 'contract_hours': 40}, {'name': 'Charlie', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 32, 'contract_hours': 37}, {'name': 'Helen', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 48, 'contract_hours': 35}], 'DesignWorks': [{'name': 'Jack', 'job': 'Analyste', 'hourly_rate': 40, 'weekly_hours_worked': 38, 'contract_hours': 40}, {'name': 'Emma', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 34, 'contract_hours': 40}, {'name': 'Ian', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 37, 'contract_hours': 35}, {'name': 'Tina', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 48, 'contract_hours': 35}, {'name': 'Oliver', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 49, 'contract_hours': 40}, {'name': 'Jack', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 33, 'contract_hours': 35}, {'name': 'Oliver', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 45, 'contract_hours': 40}, {'name': 'Rachel', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 37, 'contract_hours': 35}, {'name': 'Ian', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 43, 'contract_hours': 37}, {'name': 'Jack', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 37, 'contract_hours': 35}, {'name': 'Rachel', 'job': 'Analyste', 'hourly_rate': 40, 'weekly_hours_worked': 32, 'contract_hours': 35}, {'name': 'Helen', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 37, 'contract_hours': 35}, {'name': 'George', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 30, 'contract_hours': 40}, {'name': 'Rachel', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 48, 'contract_hours': 35}, {'name': 'Emma', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 44, 'contract_hours': 37}, {'name': 'Mike', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 32, 'contract_hours': 40}, {'name': 'Ian', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 39, 'contract_hours': 35}, {'name': 'Bob', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 45, 'contract_hours': 35}], 'ProjectLead': [{'name': 'Fred', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 49, 'contract_hours': 40}, {'name': 'Mike', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 32, 'contract_hours': 37}, {'name': 'Oliver', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 38, 'contract_hours': 35}, {'name': 'Tina', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 37, 'contract_hours': 37}, {'name': 'Linda', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 39, 'contract_hours': 37}, {'name': 'Rachel', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 48, 'contract_hours': 35}, {'name': 'Bob', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 46, 'contract_hours': 35}, {'name': 'Steve', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 44, 'contract_hours': 37}, {'name': 'Jack', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 31, 'contract_hours': 37}, {'name': 'Jack', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 46, 'contract_hours': 35}, {'name': 'Charlie', 'job': 'Manager', 'hourly_rate': 55, 'weekly_hours_worked': 43, 'contract_hours': 37}, {'name': 'Oliver', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 35, 'contract_hours': 37}, {'name': 'Nina', 'job': 'Analyste', 'hourly_rate': 40, 'weekly_hours_worked': 45, 'contract_hours': 40}, {'name': 'Steve', 'job': 'Designer', 'hourly_rate': 30, 'weekly_hours_worked': 42, 'contract_hours': 37}, {'name': 'Linda', 'job': 'Développeur', 'hourly_rate': 35, 'weekly_hours_worked': 36, 'contract_hours': 35}, {'name': 'Jack', 'job': 'Testeur', 'hourly_rate': 28, 'weekly_hours_worked': 46, 'contract_hours': 35}, {'name': 'Charlie', 'job': 'Chef de projet', 'hourly_rate': 50, 'weekly_hours_worked': 40, 'contract_hours': 35}]}
dict_keys(['TechCorp', 'DesignWorks', 'ProjectLead'])

       name             job  hourly_rate  weekly_hours_worked  contract_hours
0     Helen  Chef de projet           50                   44              37
1    Quincy         Testeur           28                   48              40
2      Fred         Manager           55                   33              40
3     Steve  Chef de projet           50                   32              40
4     Linda  Chef de projet           50                   34              35
5       Bob        Analyste           40                   35              40
6     Steve  Chef de projet           50                   50              37
7     Karen     Développeur           35                   33              40
8      Paul        Designer           30                   30              35
9       Bob     Développeur           35                   48              35
10      Bob         Manager           55                   45              35
11     Mike         Testeur           28                   33              40
12     Mike  Chef de projet           50                   43              40
13  Charlie  Chef de projet           50                   32              37
14    Helen         Testeur           28                   48              35

In [3]:
for j in TechCorp:
    print(j['weekly_hours_worked'])

44
48
33
32
34
35
50
33
30
48
45
33
43
32
48

In [4]:
def CalcSalary(d1:dict,d2:dict,d3:dict):
    print("TechCorp")
    
    for j in d1:
        if j['contract_hours'] < j['weekly_hours_worked']:
            sup_hour = j['weekly_hours_worked']-j['contract_hours']
            salary = (j['hourly_rate']*j['contract_hours'] + sup_hour * j['hourly_rate']*1.5)*4

        else:
            salary = j['hourly_rate']*j['weekly_hours_worked']*4

        
        print(f"{j['name']} | {j['job']} | Salaire mensuel : {salary:.2f} €")

    for k in d2:
        if k['contract_hours'] < k['weekly_hours_worked']:
            sup_hour = k['weekly_hours_worked']-k['contract_hours']
            salary = (k['hourly_rate']*k['contract_hours'] + sup_hour * k['hourly_rate']*1.5)*4

        else: 
            salary = k['hourly_rate']*k['weekly_hours_worked']*4

        print(f"{k['name']} | {k['job']} | Salaire mensuel : {salary:.2f} €")

    for l in d3:
        if l['contract_hours'] < l['weekly_hours_worked']:
            sup_hour = l['weekly_hours_worked']-l['contract_hours']
            salary = (l['hourly_rate']*l['contract_hours'] + sup_hour * l['hourly_rate']*1.5)*4

        else: 
            salary = l['hourly_rate']*l['weekly_hours_worked']*4

        print(f"{l['name']:<10}| {l['job']:<10}| Salaire mensuel : {salary:.2f<10} €")

In [5]:
CalcSalary(TechCorp,DesignWorks,ProjectLead)

TechCorp
Helen | Chef de projet | Salaire mensuel : 9500.00 €
Quincy | Testeur | Salaire mensuel : 5824.00 €
Fred | Manager | Salaire mensuel : 7260.00 €
Steve | Chef de projet | Salaire mensuel : 6400.00 €
Linda | Chef de projet | Salaire mensuel : 6800.00 €
Bob | Analyste | Salaire mensuel : 5600.00 €
Steve | Chef de projet | Salaire mensuel : 11300.00 €
Karen | Développeur | Salaire mensuel : 4620.00 €
Paul | Designer | Salaire mensuel : 3600.00 €
Bob | Développeur | Salaire mensuel : 7630.00 €
Bob | Manager | Salaire mensuel : 11000.00 €
Mike | Testeur | Salaire mensuel : 3696.00 €
Mike | Chef de projet | Salaire mensuel : 8900.00 €
Charlie | Chef de projet | Salaire mensuel : 6400.00 €
Helen | Testeur | Salaire mensuel : 6104.00 €
Jack | Analyste | Salaire mensuel : 6080.00 €
Emma | Designer | Salaire mensuel : 4080.00 €
Ian | Chef de projet | Salaire mensuel : 7600.00 €
Tina | Testeur | Salaire mensuel : 6104.00 €
Oliver | Chef de projet | Salaire mensuel : 10700.00 €
Jack | Designer | Salaire mensuel : 3960.00 €
Oliver | Manager | Salaire mensuel : 10450.00 €
Rachel | Testeur | Salaire mensuel : 4256.00 €
Ian | Testeur | Salaire mensuel : 5152.00 €
Jack | Chef de projet | Salaire mensuel : 7600.00 €
Rachel | Analyste | Salaire mensuel : 5120.00 €
Helen | Développeur | Salaire mensuel : 5320.00 €
George | Développeur | Salaire mensuel : 4200.00 €
Rachel | Testeur | Salaire mensuel : 6104.00 €
Emma | Chef de projet | Salaire mensuel : 9500.00 €
Mike | Manager | Salaire mensuel : 7040.00 €
Ian | Chef de projet | Salaire mensuel : 8200.00 €
Bob | Chef de projet | Salaire mensuel : 10000.00 €

ValueError: Invalid format specifier '.2f<10' for object of type 'float'

In [6]:
print(data.keys())

dict_keys(['TechCorp', 'DesignWorks', 'ProjectLead'])

In [41]:
def CalcSalary(d):
    
    print(end='\n')
    for i in d:
        print(end='\n')
        print(f"Entreprise : {i}")
        print(end='\n')

        for j in d[i]:
            if j['contract_hours'] < j['weekly_hours_worked']:
                sup_hour = j['weekly_hours_worked']-j['contract_hours']
                salary = (j['hourly_rate']*j['contract_hours'] + sup_hour * j['hourly_rate']*1.5)*4

            else:
                salary = j['hourly_rate']*j['weekly_hours_worked']*4

            j['Salary'] = salary
            print(f"{j['name']:<20} | {j['job']:<20} | Salaire mensuel : {salary:.2f} €")
        print(end='\n')
        print("===================================================================================")

In [39]:
CalcSalary(data)

Entreprise : TechCorp

Helen                | Chef de projet       | Salaire mensuel : 9500.00 €
Quincy               | Testeur              | Salaire mensuel : 5824.00 €
Fred                 | Manager              | Salaire mensuel : 7260.00 €
Steve                | Chef de projet       | Salaire mensuel : 6400.00 €
Linda                | Chef de projet       | Salaire mensuel : 6800.00 €
Bob                  | Analyste             | Salaire mensuel : 5600.00 €
Steve                | Chef de projet       | Salaire mensuel : 11300.00 €
Karen                | Développeur          | Salaire mensuel : 4620.00 €
Paul                 | Designer             | Salaire mensuel : 3600.00 €
Bob                  | Développeur          | Salaire mensuel : 7630.00 €
Bob                  | Manager              | Salaire mensuel : 11000.00 €
Mike                 | Testeur              | Salaire mensuel : 3696.00 €
Mike                 | Chef de projet       | Salaire mensuel : 8900.00 €
Charlie              | Chef de projet       | Salaire mensuel : 6400.00 €
Helen                | Testeur              | Salaire mensuel : 6104.00 €

===================================================================================

Entreprise : DesignWorks

Jack                 | Analyste             | Salaire mensuel : 6080.00 €
Emma                 | Designer             | Salaire mensuel : 4080.00 €
Ian                  | Chef de projet       | Salaire mensuel : 7600.00 €
Tina                 | Testeur              | Salaire mensuel : 6104.00 €
Oliver               | Chef de projet       | Salaire mensuel : 10700.00 €
Jack                 | Designer             | Salaire mensuel : 3960.00 €
Oliver               | Manager              | Salaire mensuel : 10450.00 €
Rachel               | Testeur              | Salaire mensuel : 4256.00 €
Ian                  | Testeur              | Salaire mensuel : 5152.00 €
Jack                 | Chef de projet       | Salaire mensuel : 7600.00 €
Rachel               | Analyste             | Salaire mensuel : 5120.00 €
Helen                | Développeur          | Salaire mensuel : 5320.00 €
George               | Développeur          | Salaire mensuel : 4200.00 €
Rachel               | Testeur              | Salaire mensuel : 6104.00 €
Emma                 | Chef de projet       | Salaire mensuel : 9500.00 €
Mike                 | Manager              | Salaire mensuel : 7040.00 €
Ian                  | Chef de projet       | Salaire mensuel : 8200.00 €
Bob                  | Chef de projet       | Salaire mensuel : 10000.00 €

===================================================================================

Entreprise : ProjectLead

Fred                 | Testeur              | Salaire mensuel : 5992.00 €
Mike                 | Développeur          | Salaire mensuel : 4480.00 €
Oliver               | Chef de projet       | Salaire mensuel : 7900.00 €
Tina                 | Manager              | Salaire mensuel : 8140.00 €
Linda                | Testeur              | Salaire mensuel : 4480.00 €
Rachel               | Designer             | Salaire mensuel : 6540.00 €
Bob                  | Manager              | Salaire mensuel : 11330.00 €
Steve                | Chef de projet       | Salaire mensuel : 9500.00 €
Jack                 | Chef de projet       | Salaire mensuel : 6200.00 €
Jack                 | Designer             | Salaire mensuel : 6180.00 €
Charlie              | Manager              | Salaire mensuel : 10120.00 €
Oliver               | Développeur          | Salaire mensuel : 4900.00 €
Nina                 | Analyste             | Salaire mensuel : 7600.00 €
Steve                | Designer             | Salaire mensuel : 5340.00 €
Linda                | Développeur          | Salaire mensuel : 5110.00 €
Jack                 | Testeur              | Salaire mensuel : 5768.00 €
Charlie              | Chef de projet       | Salaire mensuel : 8500.00 €

===================================================================================

{'TechCorp': [{'name': 'Helen',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 44,
   'contract_hours': 37,
   'Salary': 9500.0},
  {'name': 'Quincy',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 40,
   'Salary': 5824.0},
  {'name': 'Fred',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 33,
   'contract_hours': 40,
   'Salary': 7260},
  {'name': 'Steve',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 32,
   'contract_hours': 40,
   'Salary': 6400},
  {'name': 'Linda',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 34,
   'contract_hours': 35,
   'Salary': 6800},
  {'name': 'Bob',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 35,
   'contract_hours': 40,
   'Salary': 5600},
  {'name': 'Steve',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 50,
   'contract_hours': 37,
   'Salary': 11300.0},
  {'name': 'Karen',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 33,
   'contract_hours': 40,
   'Salary': 4620},
  {'name': 'Paul',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 30,
   'contract_hours': 35,
   'Salary': 3600},
  {'name': 'Bob',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 48,
   'contract_hours': 35,
   'Salary': 7630.0},
  {'name': 'Bob',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 45,
   'contract_hours': 35,
   'Salary': 11000.0},
  {'name': 'Mike',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 33,
   'contract_hours': 40,
   'Salary': 3696},
  {'name': 'Mike',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 43,
   'contract_hours': 40,
   'Salary': 8900.0},
  {'name': 'Charlie',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 32,
   'contract_hours': 37,
   'Salary': 6400},
  {'name': 'Helen',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 35,
   'Salary': 6104.0}],
 'DesignWorks': [{'name': 'Jack',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 38,
   'contract_hours': 40,
   'Salary': 6080},
  {'name': 'Emma',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 34,
   'contract_hours': 40,
   'Salary': 4080},
  {'name': 'Ian',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 37,
   'contract_hours': 35,
   'Salary': 7600.0},
  {'name': 'Tina',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 35,
   'Salary': 6104.0},
  {'name': 'Oliver',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 49,
   'contract_hours': 40,
   'Salary': 10700.0},
  {'name': 'Jack',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 33,
   'contract_hours': 35,
   'Salary': 3960},
  {'name': 'Oliver',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 45,
   'contract_hours': 40,
   'Salary': 10450.0},
  {'name': 'Rachel',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 37,
   'contract_hours': 35,
   'Salary': 4256.0},
  {'name': 'Ian',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 43,
   'contract_hours': 37,
   'Salary': 5152.0},
  {'name': 'Jack',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 37,
   'contract_hours': 35,
   'Salary': 7600.0},
  {'name': 'Rachel',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 32,
   'contract_hours': 35,
   'Salary': 5120},
  {'name': 'Helen',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 37,
   'contract_hours': 35,
   'Salary': 5320.0},
  {'name': 'George',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 30,
   'contract_hours': 40,
   'Salary': 4200},
  {'name': 'Rachel',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 35,
   'Salary': 6104.0},
  {'name': 'Emma',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 44,
   'contract_hours': 37,
   'Salary': 9500.0},
  {'name': 'Mike',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 32,
   'contract_hours': 40,
   'Salary': 7040},
  {'name': 'Ian',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 39,
   'contract_hours': 35,
   'Salary': 8200.0},
  {'name': 'Bob',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 45,
   'contract_hours': 35,
   'Salary': 10000.0}],
 'ProjectLead': [{'name': 'Fred',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 49,
   'contract_hours': 40,
   'Salary': 5992.0},
  {'name': 'Mike',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 32,
   'contract_hours': 37,
   'Salary': 4480},
  {'name': 'Oliver',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 38,
   'contract_hours': 35,
   'Salary': 7900.0},
  {'name': 'Tina',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 37,
   'contract_hours': 37,
   'Salary': 8140},
  {'name': 'Linda',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 39,
   'contract_hours': 37,
   'Salary': 4480.0},
  {'name': 'Rachel',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 48,
   'contract_hours': 35,
   'Salary': 6540.0},
  {'name': 'Bob',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 46,
   'contract_hours': 35,
   'Salary': 11330.0},
  {'name': 'Steve',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 44,
   'contract_hours': 37,
   'Salary': 9500.0},
  {'name': 'Jack',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 31,
   'contract_hours': 37,
   'Salary': 6200},
  {'name': 'Jack',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 46,
   'contract_hours': 35,
   'Salary': 6180.0},
  {'name': 'Charlie',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 43,
   'contract_hours': 37,
   'Salary': 10120.0},
  {'name': 'Oliver',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 35,
   'contract_hours': 37,
   'Salary': 4900},
  {'name': 'Nina',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 45,
   'contract_hours': 40,
   'Salary': 7600.0},
  {'name': 'Steve',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 42,
   'contract_hours': 37,
   'Salary': 5340.0},
  {'name': 'Linda',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 36,
   'contract_hours': 35,
   'Salary': 5110.0},
  {'name': 'Jack',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 46,
   'contract_hours': 35,
   'Salary': 5768.0},
  {'name': 'Charlie',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 40,
   'contract_hours': 35,
   'Salary': 8500.0}]}

In [43]:
data

{'TechCorp': [{'name': 'Helen',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 44,
   'contract_hours': 37,
   'Salary': 9500.0},
  {'name': 'Quincy',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 40,
   'Salary': 5824.0},
  {'name': 'Fred',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 33,
   'contract_hours': 40,
   'Salary': 7260},
  {'name': 'Steve',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 32,
   'contract_hours': 40,
   'Salary': 6400},
  {'name': 'Linda',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 34,
   'contract_hours': 35,
   'Salary': 6800},
  {'name': 'Bob',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 35,
   'contract_hours': 40,
   'Salary': 5600},
  {'name': 'Steve',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 50,
   'contract_hours': 37,
   'Salary': 11300.0},
  {'name': 'Karen',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 33,
   'contract_hours': 40,
   'Salary': 4620},
  {'name': 'Paul',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 30,
   'contract_hours': 35,
   'Salary': 3600},
  {'name': 'Bob',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 48,
   'contract_hours': 35,
   'Salary': 7630.0},
  {'name': 'Bob',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 45,
   'contract_hours': 35,
   'Salary': 11000.0},
  {'name': 'Mike',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 33,
   'contract_hours': 40,
   'Salary': 3696},
  {'name': 'Mike',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 43,
   'contract_hours': 40,
   'Salary': 8900.0},
  {'name': 'Charlie',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 32,
   'contract_hours': 37,
   'Salary': 6400},
  {'name': 'Helen',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 35,
   'Salary': 6104.0}],
 'DesignWorks': [{'name': 'Jack',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 38,
   'contract_hours': 40,
   'Salary': 6080},
  {'name': 'Emma',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 34,
   'contract_hours': 40,
   'Salary': 4080},
  {'name': 'Ian',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 37,
   'contract_hours': 35,
   'Salary': 7600.0},
  {'name': 'Tina',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 35,
   'Salary': 6104.0},
  {'name': 'Oliver',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 49,
   'contract_hours': 40,
   'Salary': 10700.0},
  {'name': 'Jack',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 33,
   'contract_hours': 35,
   'Salary': 3960},
  {'name': 'Oliver',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 45,
   'contract_hours': 40,
   'Salary': 10450.0},
  {'name': 'Rachel',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 37,
   'contract_hours': 35,
   'Salary': 4256.0},
  {'name': 'Ian',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 43,
   'contract_hours': 37,
   'Salary': 5152.0},
  {'name': 'Jack',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 37,
   'contract_hours': 35,
   'Salary': 7600.0},
  {'name': 'Rachel',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 32,
   'contract_hours': 35,
   'Salary': 5120},
  {'name': 'Helen',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 37,
   'contract_hours': 35,
   'Salary': 5320.0},
  {'name': 'George',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 30,
   'contract_hours': 40,
   'Salary': 4200},
  {'name': 'Rachel',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 35,
   'Salary': 6104.0},
  {'name': 'Emma',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 44,
   'contract_hours': 37,
   'Salary': 9500.0},
  {'name': 'Mike',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 32,
   'contract_hours': 40,
   'Salary': 7040},
  {'name': 'Ian',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 39,
   'contract_hours': 35,
   'Salary': 8200.0},
  {'name': 'Bob',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 45,
   'contract_hours': 35,
   'Salary': 10000.0}],
 'ProjectLead': [{'name': 'Fred',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 49,
   'contract_hours': 40,
   'Salary': 5992.0},
  {'name': 'Mike',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 32,
   'contract_hours': 37,
   'Salary': 4480},
  {'name': 'Oliver',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 38,
   'contract_hours': 35,
   'Salary': 7900.0},
  {'name': 'Tina',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 37,
   'contract_hours': 37,
   'Salary': 8140},
  {'name': 'Linda',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 39,
   'contract_hours': 37,
   'Salary': 4480.0},
  {'name': 'Rachel',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 48,
   'contract_hours': 35,
   'Salary': 6540.0},
  {'name': 'Bob',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 46,
   'contract_hours': 35,
   'Salary': 11330.0},
  {'name': 'Steve',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 44,
   'contract_hours': 37,
   'Salary': 9500.0},
  {'name': 'Jack',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 31,
   'contract_hours': 37,
   'Salary': 6200},
  {'name': 'Jack',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 46,
   'contract_hours': 35,
   'Salary': 6180.0},
  {'name': 'Charlie',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 43,
   'contract_hours': 37,
   'Salary': 10120.0},
  {'name': 'Oliver',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 35,
   'contract_hours': 37,
   'Salary': 4900},
  {'name': 'Nina',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 45,
   'contract_hours': 40,
   'Salary': 7600.0},
  {'name': 'Steve',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 42,
   'contract_hours': 37,
   'Salary': 5340.0},
  {'name': 'Linda',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 36,
   'contract_hours': 35,
   'Salary': 5110.0},
  {'name': 'Jack',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 46,
   'contract_hours': 35,
   'Salary': 5768.0},
  {'name': 'Charlie',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 40,
   'contract_hours': 35,
   'Salary': 8500.0}]}

In [55]:
def Stat_sal(d=data):

    print(end='\n')
    for i in d:
        total=0
        for j in d[i]:
            
            total+=j['Salary']
           
        avg_salary=total/(len(i))
            
        print(f" salaire moy : {avg_salary} €")

In [57]:
Stat_sal(data)

 salaire moy : 13079.25 €
 salaire moy : 11042.363636363636 €
 salaire moy : 10734.545454545454 €

In [14]:
employe= data.copy()
employe

{'TechCorp': [{'name': 'Helen',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 44,
   'contract_hours': 37},
  {'name': 'Quincy',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 40},
  {'name': 'Fred',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 33,
   'contract_hours': 40},
  {'name': 'Steve',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 32,
   'contract_hours': 40},
  {'name': 'Linda',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 34,
   'contract_hours': 35},
  {'name': 'Bob',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 35,
   'contract_hours': 40},
  {'name': 'Steve',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 50,
   'contract_hours': 37},
  {'name': 'Karen',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 33,
   'contract_hours': 40},
  {'name': 'Paul',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 30,
   'contract_hours': 35},
  {'name': 'Bob',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 48,
   'contract_hours': 35},
  {'name': 'Bob',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 45,
   'contract_hours': 35},
  {'name': 'Mike',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 33,
   'contract_hours': 40},
  {'name': 'Mike',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 43,
   'contract_hours': 40},
  {'name': 'Charlie',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 32,
   'contract_hours': 37},
  {'name': 'Helen',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 35}],
 'DesignWorks': [{'name': 'Jack',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 38,
   'contract_hours': 40},
  {'name': 'Emma',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 34,
   'contract_hours': 40},
  {'name': 'Ian',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 37,
   'contract_hours': 35},
  {'name': 'Tina',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 35},
  {'name': 'Oliver',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 49,
   'contract_hours': 40},
  {'name': 'Jack',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 33,
   'contract_hours': 35},
  {'name': 'Oliver',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 45,
   'contract_hours': 40},
  {'name': 'Rachel',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 37,
   'contract_hours': 35},
  {'name': 'Ian',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 43,
   'contract_hours': 37},
  {'name': 'Jack',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 37,
   'contract_hours': 35},
  {'name': 'Rachel',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 32,
   'contract_hours': 35},
  {'name': 'Helen',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 37,
   'contract_hours': 35},
  {'name': 'George',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 30,
   'contract_hours': 40},
  {'name': 'Rachel',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 48,
   'contract_hours': 35},
  {'name': 'Emma',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 44,
   'contract_hours': 37},
  {'name': 'Mike',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 32,
   'contract_hours': 40},
  {'name': 'Ian',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 39,
   'contract_hours': 35},
  {'name': 'Bob',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 45,
   'contract_hours': 35}],
 'ProjectLead': [{'name': 'Fred',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 49,
   'contract_hours': 40},
  {'name': 'Mike',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 32,
   'contract_hours': 37},
  {'name': 'Oliver',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 38,
   'contract_hours': 35},
  {'name': 'Tina',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 37,
   'contract_hours': 37},
  {'name': 'Linda',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 39,
   'contract_hours': 37},
  {'name': 'Rachel',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 48,
   'contract_hours': 35},
  {'name': 'Bob',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 46,
   'contract_hours': 35},
  {'name': 'Steve',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 44,
   'contract_hours': 37},
  {'name': 'Jack',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 31,
   'contract_hours': 37},
  {'name': 'Jack',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 46,
   'contract_hours': 35},
  {'name': 'Charlie',
   'job': 'Manager',
   'hourly_rate': 55,
   'weekly_hours_worked': 43,
   'contract_hours': 37},
  {'name': 'Oliver',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 35,
   'contract_hours': 37},
  {'name': 'Nina',
   'job': 'Analyste',
   'hourly_rate': 40,
   'weekly_hours_worked': 45,
   'contract_hours': 40},
  {'name': 'Steve',
   'job': 'Designer',
   'hourly_rate': 30,
   'weekly_hours_worked': 42,
   'contract_hours': 37},
  {'name': 'Linda',
   'job': 'Développeur',
   'hourly_rate': 35,
   'weekly_hours_worked': 36,
   'contract_hours': 35},
  {'name': 'Jack',
   'job': 'Testeur',
   'hourly_rate': 28,
   'weekly_hours_worked': 46,
   'contract_hours': 35},
  {'name': 'Charlie',
   'job': 'Chef de projet',
   'hourly_rate': 50,
   'weekly_hours_worked': 40,
   'contract_hours': 35}]}